# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dccee050afcd89238a3d924aa7608d5c"
name = "Pxhog"
handle = "pxhog"
application_url = "https://app.pxhog.com"
embedded = true

[build]
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_themes,write_pixels"

[auth]
redirect_urls = [
  "https://app.pxhog.com/auth/callback",
  "https://app.pxhog.com/auth/shopify/callback",
  "https://app.pxhog.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/redact" ]
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request"]
uri = "/webhooks/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = [ "shop/redact" ]
uri = "/webhooks/shop/redact"


[pos]
embedded = false
