# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dccee050afcd89238a3d924aa7608d5c"
name = "Posthog Analytics"
handle = "posthog-analytics"
application_url = "https://net-observation-taxation-interactive.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "celadonworksdev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[auth]
redirect_urls = [
  "https://net-observation-taxation-interactive.trycloudflare.com/auth/callback",
  "https://net-observation-taxation-interactive.trycloudflare.com/auth/shopify/callback",
  "https://net-observation-taxation-interactive.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://net-observation-taxation-interactive.trycloudflare.com"
subpath = "ph-analytics"
prefix = "tools"

[pos]
embedded = false
