name = "web-pixel"
type = "web_pixel_extension"


runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = false
preferences = false
sale_of_data = "disabled"

[settings]
type = "object"

[settings.fields.ph_project_api_key]
name = "Posthog Project API Key"
description = "ph_project_api_key"
type = "single_line_text_field"
