name = "web-pixel"
type = "web_pixel_extension"


runtime_context = "strict"

[customer_privacy]
analytics = false
marketing = false
preferences = false
sale_of_data = "disabled"

[settings]
type = "object"

[settings.fields.posthog_api_key]
name = "Posthog Project API Key"
description = "posthog_api_key"
type = "single_line_text_field"

[settings.fields.posthog_api_host]
name = "Posthog Project API Host"
description = "posthog_api_host"
type = "single_line_text_field"

[settings.fields.tracked_events]
name = "Tracked Events"
description = "Active events to track"
type = "single_line_text_field"


[settings.fields.data_collection_strategy]
name = "Data collection strategy"
description = "Data collection strategy"
type = "single_line_text_field"
validations =  [
  { name = "choices", value = "[\"anonymized\", \"non-anonymized\",\"non-anonymized-by-consent\"]" }
]

